import type { Metadata } from "next"
// import "./globals.css"
import "/src/styles/global.scss"
import Link from "next/link"
import React from "react"
import styles from "./layout.module.scss"

export const metadata: Metadata = {
  title: "Ludos Web App",
  description: "Generated by create next app",
}

const Header = () => {
  return (
    <header className={styles.header}>
      <nav className={styles.navigation}>
        <Link href={"/"}>Home</Link>
        <ul>
          <li>
            <Link href={"/login"}>login</Link>
          </li>
          <li>
            <Link href={"/register"}>register</Link>
          </li>
          <li>
            <Link href={"/elements"}>elements</Link>
          </li>
        </ul>
      </nav>
    </header>
  )
}

const Footer: React.FC = () => {
  return <footer className={styles.footer}>footer</footer>
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={styles.layout}>
        <Header />
        <div className={styles.mainContent}>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
