import type { Metadata } from "next"
// import "./globals.css"
import "/src/styles/global.scss"
import React from "react"
import styles from "./layout.module.scss"
import { AuthProvider } from "../context/auth"
import Header from "@/components/layout/header"
import { Poppins } from "next/font/google"

export const metadata: Metadata = {
  title: "Ludos Web App",
  description: "Generated by create next app",
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const Footer: React.FC = () => {
  return (
    <footer className={styles.footer}>
      <p>© 2025 Ludo Bourneville</p>
    </footer>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${styles.layout} ${poppins.className}`}>
        <AuthProvider>
          <Header />
          <div className={styles.mainContent}>{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
