import type { Metadata } from "next"
// import "./globals.css"
import "/src/styles/global.scss"
import React from "react"
import styles from "./layout.module.scss"
import { AuthProvider } from "../context/auth"
import Header from "@/components/layout/header"

export const metadata: Metadata = {
  title: "Ludos Web App",
  description: "Generated by create next app",
}

const Footer: React.FC = () => {
  return <footer className={styles.footer}>footer</footer>
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={styles.layout}>
        <AuthProvider>
          <Header />
          <div className={styles.mainContent}>{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
